### ISSUE TITLE
How does training queue work

### ISSUE THREAD

**Issue by LeoLiu1999** [TakingTheL/RealTime#3]
Jeffrey, can you give me a rundown of how the queue for unit training work? I have completed the AI and just need to hook it up to the computerTeam training queue. Thanks!

**Comment by DevJW2** [comment]
1) Mousepressed, puts unit into queue
2) Puts in queue based off of trainingTime of each unit
2) Tests if the unit with the least trainingTime has a cool down of zero
If yes then put out onto game field
If not then subtract one cooldown for each unit (this occurs every second)
P.S. It doesn't really work the way i want it, it may change, but that's how it currently works for now.

**Comment by LeoLiu1999** [comment]
Thanks Jeffrey
